<h1 style="color:#45CE30;font-weight:700;text-align:center;">Decision Tree</h1>

---

In [1]:
import pandas as pd

df = pd.read_csv("salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [2]:
inputs = df.drop('salary_more_then_100k',axis='columns')

In [3]:
target = df[['salary_more_then_100k']]
target.head()

   salary_more_then_100k
0                      0
1                      0
2                      1
3                      1
4                      0

### Encoding the textual data:

In [4]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [5]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])

In [6]:
inputs.head()

  company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [7]:
new_input = inputs.drop(['company','job','degree'],axis='columns')
new_input.head()

   company_n  job_n  degree_n
0          2      2         0
1          2      2         1
2          2      0         0
3          2      0         1
4          2      1         0

In [8]:
target.head()

   salary_more_then_100k
0                      0
1                      0
2                      1
3                      1
4                      0

### Splitting the data

In [9]:
import warnings
warnings.filterwarnings('ignore')

# ***Training the model with Decision Tree Classifier***

In [10]:
from sklearn import tree

model = tree.DecisionTreeClassifier()
model.fit(new_input, target)

DecisionTreeClassifier()

In [11]:
model.score(new_input, target)*100

100.0

**Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?**

In [12]:
model.predict([[2,1,0]])

array([0])

**Is salary of Google, Computer Engineer, Masters degree > 100 k ?**

In [13]:
model.predict([[2,1,1]])

array([1])