# <font style="color:#00BCA1;font-weight:700;">Cosine Similarity</font>

- Cosine similarity measures the similarity between two vectors by finding the cosine of the angle between them.
- **Cosine Similarity= `A⋅B/ ∥A∥ ∥B∥`**

In [1]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances

In [2]:
cosine_similarity([[3,1]],[[6,2]])

array([[1.]])

In [3]:
cosine_similarity([[3,0]],[[0,8]])

array([[0.]])

In [4]:
doc1 = """
iphone sales contributed to 70% of revenue. iphone demand is increasing by 20% yoy. 
the main competitor phone galaxy recorded 5% less growth compared to iphone"
"""

doc2 = """
The upside pressure on volumes for the iPhone 12 series, historical outperformance 
in the July-September time period heading into launch event, and further catalysts in relation
to outperformance for iPhone 13 volumes relative to lowered investor expectations implies a 
very attractive set up for the shares.
"""

doc3 = """
samsung's flagship product galaxy is able to penetrate more into asian markets compared to
iphone. galaxy is redesigned with new look that appeals young demographics. 60% of samsung revenues
are coming from galaxy phone sales
"""

doc4 = """
Samsung Electronics unveils its Galaxy S21 flagship, with modest spec improvements 
and a significantly lower price point. Galaxy S21 price is lower by ~20% (much like the iPhone 12A), 
which highlights Samsung's focus on boosting shipments and regaining market share.
"""

In [5]:
import pandas as pd

df = pd.DataFrame([
        {'iPhone': 3,'galaxy': 1},
        {'iPhone': 2,'galaxy': 0},
        {'iPhone': 1,'galaxy': 3},
        {'iPhone': 1,'galaxy': 2},
    ],
    index=[
        "doc1",
        "doc2",
        "doc3",
        "doc4"
    ])

df

      iPhone  galaxy
doc1       3       1
doc2       2       0
doc3       1       3
doc4       1       2

In [6]:
df.loc["doc1":"doc1"]

      iPhone  galaxy
doc1       3       1

In [7]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc2":"doc2"])

array([[0.9486833]])

In [8]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc3":"doc3"])

array([[0.6]])

In [9]:
cosine_similarity(df.loc["doc3":"doc3"],df.loc["doc4":"doc4"])

array([[0.98994949]])

In [10]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc4":"doc4"])

array([[0.70710678]])

In [11]:
cosine_distances(df.loc["doc1":"doc1"],df.loc["doc4":"doc4"])

array([[0.29289322]])

In [12]:
1-0.70710678

0.29289321999999995